## Датасет собран из базы данных переписи 1994 года и содержит данные о доходах.
### Информация о данных:
* age: continuous.
* workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
* fnlwgt: continuous.
* education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, * Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
* education-num: continuous.
* marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
* occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
* relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
* race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
* sex: Female, Male.
* capital-gain: continuous.
* capital-loss: continuous.
* hours-per-week: continuous.
* native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.
* salary: >50K,<=50K

## Проведите анализ данных при помощи Pandas выполнив поставленные задачи.
####

In [52]:
import pandas as pd

In [53]:
# загружаем датасет
data = pd.read_csv("./data/adult.data.csv")
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

**1. Посчитайте, сколько мужчин и женщин (признак *sex*) представлено в этом датасете**

In [54]:
data['sex'].value_counts()

sex
Male      21790
Female    10771
Name: count, dtype: int64

**2. Каков средний возраст мужчин (признак *age*) по всему датасету?**

In [55]:
data.loc[data['sex']=='Male','age'].mean()

np.float64(39.43354749885268)

**3. Какова доля граждан Соединенных Штатов (признак *native-country*)?**

In [56]:
(data['native-country'] == 'United-States').mean()

np.float64(0.895857006848684)

**4-5. Рассчитайте среднее значение и среднеквадратичное отклонение возраста тех, кто получает более 50K в год (признак *salary*) и тех, кто получает менее 50K в год**

In [57]:
data.groupby('salary')['age'].agg(['mean','std'])

             mean        std
salary
<=50K   36.783738  14.020088
>50K    44.249841  10.519028

**6. Правда ли, что люди, которые получают больше 50k, имеют минимум высшее образование? (признак *education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters* или *Doctorate*)**

In [58]:
higher = ['Bachelors','Prof-school','Masters','Doctorate']

rich_education = data.loc[data['salary'] == '>50K', 'education']

is_higher = rich_education.isin(higher)

all_higher = is_higher.all()      
share_higher = is_higher.mean() 

print(all_higher)
print(f"доля высшего образования среди богатых: {share_higher:.2f}")

False
доля высшего образования среди богатых: 0.50

**7. Выведите статистику возраста для каждой расы (признак *race*) и каждого пола. Используйте *groupby* и *describe*. Найдите таким образом максимальный возраст мужчин расы *Asian-Pac-Islander*.**

In [59]:
result = data.groupby(['race', 'sex']).describe()
print(result)
print(f"Максимальный возраст среди Asian-Pac-Islander мужского пола: {result.loc[('Asian-Pac-Islander', 'Male'), ('age', 'max')]}")

                               age                                          \
                             count       mean        std   min   25%   50%
race               sex
Amer-Indian-Eskimo Female    119.0  37.117647  13.114991  17.0  27.0  36.0
                   Male      192.0  37.208333  12.049563  17.0  28.0  35.0
Asian-Pac-Islander Female    346.0  35.089595  12.300845  17.0  25.0  33.0
                   Male      693.0  39.073593  12.883944  18.0  29.0  37.0
Black              Female   1555.0  37.854019  12.637197  17.0  28.0  37.0
                   Male     1569.0  37.682600  12.882612  17.0  27.0  36.0
Other              Female    109.0  31.678899  11.631599  17.0  23.0  29.0
                   Male      162.0  34.654321  11.355531  17.0  26.0  32.0
White              Female   8642.0  36.811618  14.329093  17.0  25.0  35.0
                   Male    19174.0  39.652498  13.436029  17.0  29.0  38.0

                                         fnlwgt                 ...  \
                             75%   max    count           mean  ...
race               sex                                          ...
Amer-Indian-Eskimo Female  46.00  80.0    119.0  112950.731092  ...
                   Male    45.00  82.0    192.0  125715.364583  ...
Asian-Pac-Islander Female  43.75  75.0    346.0  147452.075145  ...
                   Male    46.00  90.0    693.0  166175.865801  ...
Black              Female  46.00  90.0   1555.0  212971.387781  ...
                   Male    46.00  90.0   1569.0  242920.644997  ...
Other              Female  39.00  74.0    109.0  172519.642202  ...
                   Male    42.00  77.0    162.0  213679.104938  ...
White              Female  46.00  90.0   8642.0  183549.966906  ...
                   Male    49.00  90.0  19174.0  188987.386148  ...

                          capital-loss         hours-per-week             \
                                   75%     max          count       mean
race               sex
Amer-Indian-Eskimo Female          0.0  1721.0          119.0  36.579832
                   Male            0.0  1980.0          192.0  42.197917
Asian-Pac-Islander Female          0.0  2258.0          346.0  37.439306
                   Male            0.0  2457.0          693.0  41.468975
Black              Female          0.0  4356.0         1555.0  36.834084
                   Male            0.0  2824.0         1569.0  39.997451
Other              Female          0.0  1740.0          109.0  35.926606
                   Male            0.0  2179.0          162.0  41.851852
White              Female          0.0  4356.0         8642.0  36.296691
                   Male            0.0  3770.0        19174.0  42.668822


                                 std  min   25%   50%   75%   max
race               sex
Amer-Indian-Eskimo Female  11.046509  4.0  35.0  40.0  40.0  84.0
                   Male    11.596280  3.0  40.0  40.0  45.0  84.0
Asian-Pac-Islander Female  12.479459  1.0  35.0  40.0  40.0  99.0
                   Male    12.387563  1.0  40.0  40.0  45.0  99.0
Black              Female   9.419960  2.0  35.0  40.0  40.0  99.0
                   Male    10.909413  1.0  40.0  40.0  40.0  99.0
Other              Female  10.300761  6.0  30.0  40.0  40.0  65.0
                   Male    11.084779  5.0  40.0  40.0  40.0  98.0
White              Female  12.190951  1.0  30.0  40.0  40.0  99.0
                   Male    12.194633  1.0  40.0  40.0  50.0  99.0

[10 rows x 48 columns]
Максимальный возраст среди Asian-Pac-Islander мужского пола: 90.0

**8. Среди кого больше доля зарабатывающих много (>50K): среди женатых или холостых мужчин (признак *marital-status*)? Женатыми считаем тех, у кого *marital-status* начинается с *Married* (Married-civ-spouse, Married-spouse-absent или Married-AF-spouse), остальных считаем холостыми.**

In [60]:
married = ['Married-civ-spouse', 'Married-AF-spouse', 'Married-spouse-absent']

is_married = data['marital-status'].isin(married)

res = (data['salary'] == '>50K').groupby(is_married).mean()

res_idx = res.idxmax()
res_label = 'married' if res_idx else 'unmarried'

print(res_label, res[res_idx])

married 0.43692028280469614

**9. Какое максимальное число часов человек работает в неделю (признак *hours-per-week*)? Сколько людей работают такое количество часов и каков среди них процент зарабатывающих много?**

In [61]:
max_work_hours = data['hours-per-week'].max()

is_max_worker = data['hours-per-week'] == max_work_hours

max_workers_salaries = data.loc[is_max_worker, 'salary']

max_workers_count = len(max_workers_salaries)
rich_percentage = (max_workers_salaries == '>50K').mean() * 100

print(f"Максимальное количество рабочих часов: {max_work_hours}")
print(f"Количество работников, работающих максимальное количество часов: {max_workers_count}")
print(f"Процент зарабатывающих >50K среди них: {rich_percentage:.2f}%")

Максимальное количество рабочих часов: 99
Количество работников, работающих максимальное количество часов: 85
Процент зарабатывающих >50K среди них: 29.41%

**10. Посчитайте среднее время работы (*hours-per-week*) зарабатывающих мало и много (*salary*) для каждой страны (*native-country*).**

In [62]:
data.groupby(['native-country', 'salary'])['hours-per-week'].mean()

native-country  salary
?               <=50K     40.164760
                >50K      45.547945
Cambodia        <=50K     41.416667
                >50K      40.000000
Canada          <=50K     37.914634
                            ...
United-States   >50K      45.505369
Vietnam         <=50K     37.193548
                >50K      39.200000
Yugoslavia      <=50K     41.600000
                >50K      49.500000
Name: hours-per-week, Length: 82, dtype: float64

**11.Сгруппируйте людей по возрастным группам *young*, *adult*, *retiree*, где:**
* *young* соответствует 16-35 лет
* *adult* - 35-70 лет
* *retiree* - 70-100 лет

**Проставьте название соответсвтуещей группы для каждого человека в новой колонке AgeGroup**

In [63]:
data['AgeGroup'] = pd.cut(data['age'], bins=[15, 35, 70, 100], labels=['young', 'adult', 'retiree'])

data.head(5)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary,AgeGroup
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,adult
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,adult
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,adult
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,adult
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,young

**12-13. Определите количество зарабатывающих >50K в каждой из возрастных групп (колонка AgeGroup), а также выведите название возрастной группы, в которой чаще зарабатывают больше 50К (>50K)**

In [68]:
age_analysis = (
    (data['salary'] == '>50K')
    .groupby(data['AgeGroup'], observed=True)
    .agg(['sum', 'mean']) 
    .rename(columns={'sum': 'count >50K', 'mean': 'share >50K'})
)

print(age_analysis)
best_group = age_analysis['share >50K'].idxmax()
best_percentage = age_analysis['share >50K'].max()

print(f"\nГруппа, в которой чаще всего зарабатывают >50K: {best_group}")
print(f"Доля >50K в этой группе: {best_percentage:.2%}")

          count >50K  share >50K
AgeGroup
young           1705    0.114238
adult           6042    0.353416
retiree           94    0.174074

Группа, в которой чаще всего зарабатывают >50K: adult
Доля >50K в этой группе: 35.34%

**14. Сгруппируйте людей по типу занятости (колонка occupation) и определите количество людей в каждой группе. После чего напишите функциюю фильтрации filter_func, которая будет возвращать только те группы, в которых средний возраст (колонка age) не больше 40 и в которых все работники отрабатывают более 5 часов в неделю (колонка hours-per-week)**

In [78]:
grouped = (
    data
    .groupby('occupation')
    .agg(mean_age=('age','mean'), min_hours=('hours-per-week','min'), count=('age','size'))
)

print(grouped.loc[:, ['count']])

def filter_func(x):
    return (x['mean_age'] <= 40) & (x['min_hours'] > 5).all()

filtered = grouped[grouped.apply(filter_func, axis=1)]

print(filtered)

                   count
occupation
?                   1843
Adm-clerical        3770
Armed-Forces           9
Craft-repair        4099
Exec-managerial     4066
Farming-fishing      994
Handlers-cleaners   1370
Machine-op-inspct   2002
Other-service       3295
Priv-house-serv      149
Prof-specialty      4140
Protective-serv      649
Sales               3650
Tech-support         928
Transport-moving    1597
               mean_age  min_hours  count
occupation
Armed-Forces  30.222222          8      9